server:
  port: 8081

spring:
  datasource:
    username: root
    password: Password786
    url: jdbc:mysql://localhost:3306/sbr_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
