server:
  port: 8081

spring:
  datasource:
    username: ${env.SQL_USERNAME}
    password: ${env.SQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/${env.SQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
