

spring:
  datasource:
    username: sql6693175
    password: lAHmYrjwnx
    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6693175
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
